'use strict';
const $ = s => document.querySelector(s);
let data, revision, csrf, publishedIds = [], selected = 'academy', unsaved = false, draftDirty = false, busy = false, lastSaved = 0;
const labels = {academy:'Portada de Academia',upcoming:'Próximas convocatorias',title:'Título',subtitle:'Subtítulo',description:'Descripción',category:'Categoría',cardDescription:'Texto de la tarjeta',image:'Imagen principal',imageSmall:'Imagen para celular',imageWide:'Fondo del banner',sectionImage:'Fondo de las secciones',imageAlt:'Descripción de la imagen',introTitle:'Título introductorio',introText:'Texto introductorio',programsTitle:'Título del catálogo',programsText:'Descripción del catálogo',features:'Beneficios del banner',edition:'Edición',status:'Inscripciones',startDate:'Fecha de inicio',startLabel:'Texto de fecha / convocatoria',schedule:'Horario',modality:'Modalidad',hours:'Horas',sessions:'Sesiones',pricing:'Precios',currency:'Moneda',regular:'Precio regular (USD)',launch:'Precio de lanzamiento (USD)',launchEndsAt:'Fin del lanzamiento (con zona horaria)',note:'Nota',brochureUrl:'Enlace al brochure',whatsappUrl:'Enlace de WhatsApp',checkoutUrl:'Enlace de inscripción',contactUrl:'Enlace de contacto',registrationNote:'Nota de inscripción',learning:'Qué aprenderás',curriculum:'Contenido del programa',modules:'Módulos / sesiones',specialization:'Especialización',instructors:'Docentes',name:'Nombre',credentials:'Credenciales',methodology:'Metodología',applied:'Aplicación práctica',outcomes:'Qué lograrás',groups:'Pestañas de competencias',items:'Elementos',certificate:'Certificación',lab:'Laboratorio',proof:'Por qué MALBA PMC',stats:'Cifras',final:'Cierre y llamado a la acción',theme:'Colores del programa',accent:'Acento',accentDark:'Color de botones y textos',soft:'Fondo claro',navy:'Fondo oscuro',points:'Puntos',paragraphs:'Párrafos',value:'Valor',label:'Etiqueta',binding:'Dato automático',tools:'Herramientas',toolsTitle:'Título de herramientas',sectors:'Sectores',id:'Identificador',slug:'URL del programa',lead:'Texto principal',number:'Número',text:'Texto',body:'Contenido'};
const imageKeys = new Set(['image','imageSmall','imageWide','sectionImage']);
const statuses = {consultar:'Consultar próxima edición',abierto:'Inscripciones abiertas',proximamente:'Próximamente',agotado:'Inscripciones cerradas'};
const el = (tag,props={},children=[])=>{const x=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(k==='text')x.textContent=v;else if(k==='class')x.className=v;else x.setAttribute(k,v);}for(const c of children)x.append(c);return x;};
const date = t=>new Date(t*1000).toLocaleString('es-PE',{dateStyle:'short',timeStyle:'short'});
const clone = x=>JSON.parse(JSON.stringify(x));
function message(text,error=false){const x=$('#message');x.hidden=!text;x.textContent=text;x.classList.toggle('error',error);}
function markChanged(){unsaved=true;updateStatus();}
function updateStatus(){const x=$('#save-state');x.textContent=unsaved?'Cambios sin guardar':draftDirty?'Borrador guardado · pendiente de publicar':'Contenido publicado';if(lastSaved&&!unsaved)x.textContent+=' · '+date(lastSaved);x.classList.toggle('unsaved',unsaved||draftDirty);}
async function request(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf||''}:{},body:body?JSON.stringify(body):undefined});const result=await r.json();if(!r.ok){if(r.status===401&&path!='/api/login'){showLogin();}throw Error(result.error||'No se pudo completar la operación.');}return result;}
function showLogin(){csrf=null;$('#app').hidden=true;$('#login').hidden=false;$('#loading').hidden=true;}
async function loadContent(){const r=await request('/api/content');data=r.data;revision=r.revision;publishedIds=r.publishedIds;draftDirty=r.dirty;lastSaved=r.updated;unsaved=false;renderNavigation();renderEditor();updateStatus();}
function renderNavigation(){const nav=$('#navigation');nav.replaceChildren();for(const [id,title] of [['academy','Academia'],['upcoming','Convocatorias'],...data.programs.map(p=>[p.id,p.title])]){const p=data.programs.find(x=>x.id===id);const button=el('button',{type:'button',class:'nav-button'+(selected===id?' active':''),'aria-current':selected===id?'page':'false'});if(p)button.append(el('img',{src:asset(p.imageSmall),alt:''}));const span=el('span',{text:title});if(p)span.append(el('small',{text:statuses[p.status]}));button.append(span);button.addEventListener('click',()=>{selected=id;renderNavigation();renderEditor();message('');});nav.append(button);}}
function asset(value){return value.startsWith('https://')?value:'/'+value;}
function field(obj,key,path){const value=obj[key];const name=labels[key]||(typeof key==='number'?'Texto del elemento':key);
 if(Array.isArray(value))return collection(obj,key,path);
 if(value&&typeof value==='object'){const box=el('div',{class:'nested'},[el('h3',{text:name}),objectFields(value,path)]);if(['certificate','lab'].includes(key)){const remove=el('button',{type:'button',class:'add-item',text:'Desactivar sección'});remove.addEventListener('click',()=>{obj[key]=null;markChanged();renderEditor();});box.append(remove);}return box;}
 const wrapper=el('div',{class:'field'+(typeof value==='string'&&value.length>90?' wide':'')+(imageKeys.has(key)?' image-field':'')});
 const label=el('label',{text:name});const numeric=typeof value==='number'||['regular','launch'].includes(key);let input;
 if(key==='status'||key==='currency'||key==='binding'){input=el('select');const choices=key==='status'?statuses:key==='currency'?{USD:'USD'}:{'':'Valor manual',hours:'Horas del programa',sessions:'Sesiones del programa',start:'Fecha del programa'};for(const [val,text]of Object.entries(choices))input.append(el('option',{value:val,text}));input.value=value||'';}
 else if(typeof value==='boolean'){input=el('input',{type:'checkbox'});input.checked=value;}
 else {const multiline=!imageKeys.has(key)&&!String(key).toLowerCase().endsWith('url')&&(String(value||'').length>90||['description','subtitle','cardDescription','introText','registrationNote','paragraphs','points'].includes(key));input=el(multiline?'textarea':'input',{...(multiline?{rows:3}:{type:key==='startDate'?'date':numeric?'number':'text'}),...(numeric?{min:0,step:['hours','sessions'].includes(key)?'1':'0.01'}:{})});input.value=value??'';}
 input.dataset.path=path.join('.');input.setAttribute('aria-label',name);
 if(key==='id'||key==='slug'&&publishedIds.includes(obj.id)){input.readOnly=true;}
 const onInput=()=>{if(input.type==='checkbox')obj[key]=input.checked;else if(numeric)obj[key]=input.value===''?null:Number(input.value);else obj[key]=input.value;markChanged();};
 input.addEventListener('input',onInput);label.append(input);wrapper.append(label);
 if(key==='slug')wrapper.append(el('div',{class:'field-hint',text:publishedIds.includes(obj.id)?'URL conservada para mantener los enlaces existentes.':'Ruta pública. Usa letras minúsculas, números y guiones.'}));
 if(key==='launchEndsAt')wrapper.append(el('div',{class:'field-hint',text:'Ejemplo: 2027-03-01T00:00:00-05:00. La promoción se retira al vencer.'}));
 if(value===null&&!numeric&&!['startDate','launchEndsAt'].includes(key)){input.disabled=true;wrapper.append(el('div',{class:'field-hint',text:'Esta sección no está activada en este programa.'}));const template=data.programs.find(p=>p[key]&&typeof p[key]==='object');if(template&&['certificate','lab'].includes(key)){const add=el('button',{type:'button',class:'add-item',text:'Activar sección'});add.addEventListener('click',()=>{obj[key]=clone(template[key]);markChanged();renderEditor();});wrapper.append(add);}}
 if(imageKeys.has(key)){const img=el('img',{src:asset(String(value||'')),alt:'Vista previa de '+name});img.addEventListener('error',()=>img.hidden=true);input.addEventListener('input',()=>{img.hidden=false;img.src=asset(input.value);});const upload=el('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'Subir '+name});upload.addEventListener('change',async()=>{if(!upload.files[0])return;try{const file=upload.files[0];if(file.size>5*1024*1024)throw Error('La imagen debe pesar menos de 5 MB.');upload.disabled=true;const bytes=new Uint8Array(await file.arrayBuffer());let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await request('/api/upload',{content:btoa(str)});obj[key]=r.path;input.value=r.path;img.hidden=false;img.src=asset(r.path);markChanged();message('Imagen subida. Guarda el borrador para conservarla en este campo.');}catch(e){message(e.message,true);}finally{upload.disabled=false;upload.value='';}});wrapper.append(img,upload,el('div',{class:'field-hint',text:'PNG, JPG o WebP · máximo 5 MB. Sube una imagen o indica una URL HTTPS.'}));}
 return wrapper;
}
function objectFields(obj,path=[],keys=Object.keys(obj)){const grid=el('div',{class:'fields'});for(const key of keys)grid.append(field(obj,key,[...path,key]));return grid;}
function blank(value){if(Array.isArray(value))return value.map(blank);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,imageKeys.has(k)||k==='binding'?v:blank(v)]));if(typeof value==='number')return value;if(typeof value==='string')return '';return value;}
function collection(obj,key,path){const values=obj[key];const box=el('div',{class:'collection'});box.append(el('h3',{text:labels[key]||key}));let template=values.length?clone(values[values.length-1]):key==='tools'?{title:'',description:''}:'';
 const draw=()=>{box.replaceChildren(el('h3',{text:labels[key]||key}));values.forEach((value,i)=>{const item=el('div',{class:'collection-item'});const tools=el('div',{class:'item-tools'});for(const [text,title,handler]of [['↑','Mover arriba',()=>{if(i){[values[i-1],values[i]]=[values[i],values[i-1]];markChanged();draw();}}],['↓','Mover abajo',()=>{if(i<values.length-1){[values[i+1],values[i]]=[values[i],values[i+1]];markChanged();draw();}}],['Quitar','Quitar elemento',()=>{values.splice(i,1);markChanged();draw();}]]){const b=el('button',{type:'button',text,'aria-label':title+' '+(i+1)});b.addEventListener('click',handler);tools.append(b);}item.append(el('div',{class:'item-head'},[el('strong',{text:'Elemento '+(i+1)}),tools]));if(value&&typeof value==='object'&&!Array.isArray(value))item.append(objectFields(value,[...path,i]));else item.append(field(values,i,[...path,i]));box.append(item);});const add=el('button',{type:'button',class:'add-item',text:'＋ Añadir elemento'});add.addEventListener('click',()=>{values.push(blank(template));markChanged();draw();});box.append(add);};draw();return box;}
function panel(title,obj,path,keys,open=false){const d=el('details',{class:'panel'},[el('summary',{text:title}),el('div',{class:'panel-body'},[objectFields(obj,path,keys)])]);d.open=open;return d;}
function renderEditor(){const editor=$('#editor');editor.replaceChildren();const p=data.programs.find(x=>x.id===selected);$('#page-title').textContent=p?p.title:selected==='academy'?'Academia':'Próximas convocatorias';$('#page-description').textContent=p?'Edita su presentación, inscripciones y contenido.':selected==='academy'?'Configura el banner y la presentación de tu catálogo.':'Prepara los textos de las próximas ediciones.';
 if(!p){const section=data[selected];if(selected==='academy'){editor.append(panel('Banner de Academia',section,[selected],['title','subtitle','image','imageSmall','imageAlt'],true),panel('Presentación del catálogo',section,[selected],['programsTitle','programsText']),panel('Beneficios del banner',section,[selected],['features']));}else editor.append(panel('Presentación y contacto',section,[selected],Object.keys(section),true));return;}
 const order=el('div',{class:'program-order'});for(const [text,delta]of [['← Antes en el catálogo',-1],['Después en el catálogo →',1]]){const b=el('button',{type:'button',text});b.addEventListener('click',()=>{const i=data.programs.indexOf(p),j=i+delta;if(j>=0&&j<data.programs.length){[data.programs[i],data.programs[j]]=[data.programs[j],data.programs[i]];markChanged();renderNavigation();}});order.append(b);}editor.append(order);
 const path=['programs',data.programs.indexOf(p)];
 editor.append(panel('Presentación del programa',p,path,['title','category','description','cardDescription','edition','id','slug'],true));
 editor.append(panel('Fechas, duración e inscripciones',p,path,['status','startDate','startLabel','hours','sessions','modality','schedule','registrationNote']));
 const prices=panel('Precios y enlaces',p,path,['pricing','brochureUrl','checkoutUrl','whatsappUrl']);prices.querySelector('.panel-body').prepend(el('p',{class:'notice',text:'Estos precios son los visibles en la web. Verifica que WooCommerce cobre el mismo importe antes de abrir inscripciones.'}));editor.append(prices);
 editor.append(panel('Imágenes y colores',p,path,['image','imageSmall','imageWide','imageAlt','sectionImage','theme']));
 for(const key of ['learning','curriculum','specialization','instructors','methodology','applied','outcomes','certificate','lab','proof','final'])editor.append(panel(labels[key],p,path,[key]));
}
async function action(kind){if(busy)return;busy=true;document.querySelectorAll('.actions button').forEach(b=>b.disabled=true);message(kind==='preview'?'Preparando vista previa…':kind==='publish'?'Publicando los cambios…':'Guardando borrador…');let previewWindow;if(kind==='preview')previewWindow=window.open('about:blank','_blank');try{const r=await request('/api/'+(kind==='save'?'draft':kind),{data,revision});if(kind==='preview'){if(previewWindow){previewWindow.opener=null;previewWindow.location.href=r.url;}else message('Vista previa lista. Permite ventanas emergentes para abrirla.');}else{revision=r.revision;lastSaved=r.updated;unsaved=false;draftDirty=kind!=='publish';if(kind==='publish')publishedIds=data.programs.map(p=>p.id);updateStatus();message(kind==='publish'?'Cambios publicados. Ya puedes verlos en la web de prueba.':'Borrador guardado. La web pública todavía conserva la edición anterior.');renderNavigation();}}catch(e){previewWindow?.close();message(e.message,true);}finally{busy=false;document.querySelectorAll('.actions button').forEach(b=>b.disabled=false);}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('#login-error').textContent='';try{const form=new FormData(e.target);const r=await request('/api/login',Object.fromEntries(form));csrf=r.csrf;$('#user-label').textContent='Sesión de '+r.username;await loadContent();e.target.reset();$('#login').hidden=true;$('#app').hidden=false;}catch(err){$('#login-error').textContent=err.message;}finally{b.disabled=false;}});
$('#save').addEventListener('click',()=>action('save'));$('#preview').addEventListener('click',()=>action('preview'));
$('#publish').addEventListener('click',()=>{$('#publish-dialog').returnValue='';$('#publish-dialog').showModal();});$('#publish-dialog').addEventListener('close',()=>{if($('#publish-dialog').returnValue==='publish')action('publish');});
$('#logout').addEventListener('click',async()=>{if(unsaved&&!confirm('Tienes cambios sin guardar. ¿Cerrar sesión?'))return;try{await request('/api/logout',{});unsaved=false;data=null;showLogin();}catch(e){message(e.message,true);}});
$('#history').addEventListener('click',async()=>{try{const history=await request('/api/history');const list=$('#history-list');list.replaceChildren();history.forEach((h,i)=>{const text=el('div',{text:date(h.created)},[el('small',{text:h.username+(i===0?' · Publicación actual':'')})]);const b=el('button',{type:'button',class:'button secondary',text:'Recuperar'});b.addEventListener('click',async()=>{if(!confirm('¿Cargar esta publicación como borrador? Reemplazará las ediciones sin publicar.'))return;try{const r=await request('/api/restore',{id:h.id,revision});data=r.data;revision=r.revision;lastSaved=r.updated;unsaved=false;draftDirty=true;selected='academy';renderNavigation();renderEditor();updateStatus();$('#history-dialog').close();message('Versión recuperada como borrador. Revísala antes de publicar.');}catch(e){message(e.message,true);$('#history-dialog').close();}});list.append(el('div',{class:'history-item'},[text,b]));});$('#history-dialog').showModal();}catch(e){message(e.message,true);}});
$('#new-program').addEventListener('click',()=>{const select=$('#create-form select');select.replaceChildren(...data.programs.map(p=>el('option',{value:p.id,text:p.title})));$('#create-dialog').showModal();});
$('#create-form').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(data.programs.some(p=>p.id===f.id||p.slug===f.slug)){alert('El identificador y la URL deben ser únicos.');return;}const p=clone(data.programs.find(p=>p.id===f.template));Object.assign(p,{id:f.id,slug:f.slug,title:f.title,status:'proximamente',startDate:null,startLabel:'Fecha por confirmar',checkoutUrl:'',edition:'Primera edición'});p.pricing.regular=null;p.pricing.launch=null;p.pricing.launchEndsAt=null;data.programs.push(p);selected=p.id;markChanged();renderNavigation();renderEditor();$('#create-dialog').close();e.target.reset();message('Nuevo programa creado en el borrador. Revisa las imágenes y todos los textos heredados antes de publicar.');});
for(const dialog of document.querySelectorAll('dialog')){const close=dialog.querySelector('.dialog-close[type="button"]');close?.addEventListener('click',()=>dialog.close());}
window.addEventListener('beforeunload',e=>{if(unsaved){e.preventDefault();e.returnValue='';}});
(async()=>{try{const session=await request('/api/session');if(!session.authenticated){showLogin();return;}csrf=session.csrf;$('#user-label').textContent='Sesión de '+session.username;await loadContent();$('#app').hidden=false;$('#loading').hidden=true;}catch(e){showLogin();$('#login-error').textContent=e.message;}})();
