'use strict';
const $ = s => document.querySelector(s);
let area='academy',publicationFilter='all',publicationQuery='',publicationDraft=null;
let changeCounter=0,pendingUploads=0;
let data, revision, csrf, publishedIds = [], selected = 'overview', unsaved = false, draftDirty = false, busy = false, lastSaved = 0;
const labels = {pdfUrl:'Archivo PDF',pages:'Número de páginas',catalogTitle:'Título del catálogo',catalogText:'Texto del catálogo',academy:'Portada de Academia',upcoming:'Próximas convocatorias',title:'Título',subtitle:'Subtítulo',description:'Descripción',category:'Categoría',cardDescription:'Texto de la tarjeta',image:'Imagen principal',imageSmall:'Imagen para celular',imageWide:'Fondo del banner',sectionImage:'Fondo de las secciones',imageAlt:'Descripción de la imagen',introTitle:'Título introductorio',introText:'Texto introductorio',programsTitle:'Título del catálogo',programsText:'Descripción del catálogo',features:'Beneficios del banner',edition:'Edición',status:'Inscripciones',startDate:'Fecha de inicio',startLabel:'Texto de fecha / convocatoria',schedule:'Horario',modality:'Modalidad',hours:'Horas',sessions:'Sesiones',pricing:'Precios',currency:'Moneda',regular:'Precio regular (USD)',launch:'Precio de lanzamiento (USD)',launchEndsAt:'Fin del lanzamiento (con zona horaria)',note:'Nota',brochureUrl:'Enlace al brochure',whatsappUrl:'Enlace de WhatsApp',checkoutUrl:'Enlace de inscripción',contactUrl:'Enlace de contacto',registrationNote:'Nota de inscripción',learning:'Qué aprenderás',curriculum:'Contenido del programa',modules:'Módulos / sesiones',specialization:'Especialización',instructors:'Docentes',name:'Nombre',credentials:'Credenciales',methodology:'Metodología',applied:'Aplicación práctica',outcomes:'Qué lograrás',groups:'Pestañas de competencias',items:'Elementos',certificate:'Certificación',lab:'Laboratorio',proof:'Por qué MALBA PMC',stats:'Cifras',final:'Cierre y llamado a la acción',theme:'Colores del programa',accent:'Acento',accentDark:'Color de botones y textos',soft:'Fondo claro',navy:'Fondo oscuro',points:'Puntos',paragraphs:'Párrafos',value:'Valor',label:'Etiqueta',binding:'Dato automático',tools:'Herramientas',toolsTitle:'Título de herramientas',sectors:'Sectores',id:'Identificador',slug:'URL del programa',lead:'Texto principal',number:'Número',text:'Texto',body:'Contenido'};
const imageKeys = new Set(['image','imageSmall','imageWide','sectionImage']);
const statuses = {consultar:'Consultar próxima edición',abierto:'Inscripciones abiertas',proximamente:'Próximamente',agotado:'Inscripciones cerradas'};
const el = (tag,props={},children=[])=>{const x=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(k==='text')x.textContent=v;else if(k==='class')x.className=v;else x.setAttribute(k,v);}for(const c of children)x.append(c);return x;};
const date = t=>new Date(t*1000).toLocaleString('es-PE',{dateStyle:'short',timeStyle:'short'});
const clone = x=>JSON.parse(JSON.stringify(x));
let messageTimer;function message(text,error=false){if(wizardProgram&&$('#create-dialog').open){wizardError(text);return;}clearTimeout(messageTimer);const x=$('#message');x.hidden=!text;x.textContent=text;x.classList.toggle('error',error);if(text&&!error)messageTimer=setTimeout(()=>x.hidden=true,9000);}
function markChanged(){if(publicationDraft&&$('#publication-dialog').open)return;if(wizardProgram&&$('#create-dialog').open){wizardDirty=true;return;}changeCounter++;unsaved=true;updateStatus();}
function updateStatus(){const x=$('#save-state');x.textContent=unsaved?'Cambios sin guardar':draftDirty?'Borrador guardado · pendiente de publicar':'Contenido publicado';if(lastSaved&&!unsaved)x.textContent+=' · '+date(lastSaved);x.classList.toggle('unsaved',unsaved||draftDirty);}
async function request(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf||''}:{},body:body?JSON.stringify(body):undefined});const result=await r.json();if(!r.ok){if(r.status===401&&path!='/api/login'){showLogin();}throw Error(result.error||'No se pudo completar la operación.');}return result;}
function showLogin(){csrf=null;$('#app').hidden=true;$('#login').hidden=false;$('#loading').hidden=true;}
async function loadContent(){const r=await request('/api/content');data=r.data;revision=r.revision;publishedIds=r.publishedIds;draftDirty=r.dirty;lastSaved=r.updated;unsaved=false;renderNavigation();renderEditor();updateStatus();}
function renderNavigation(){const nav=$('#navigation');nav.replaceChildren();for(const [id,title] of [['home','Inicio'],['academy','Academia'],['digital','Soluciones digitales'],['publications','Publicaciones'],['about','Nosotros'],['contact','Contacto']]){const enabled=['academy','publications'].includes(id),active=id===area;const button=el('button',{type:'button',class:'nav-button'+(active?' active':''),'aria-current':active?'page':'false'});const span=el('span',{text:title});if(!enabled){button.disabled=true;span.append(el('small',{text:'Próximamente'}));}button.append(span);if(enabled)button.addEventListener('click',()=>{area=id;selected='overview';renderNavigation();renderEditor();message('');});nav.append(button);}}
const visibility=p=>p.visibility||'public';
const visibilityLabels={public:'Visible',hidden:'Deshabilitado',deleted:'En papelera'};
const editorTabs=[['presentation','General'],['media','Imágenes'],['enrollment','Inscripciones'],['content','Contenido'],['teaching','Docentes y método'],['closing','Cierre']];
let activeTab='presentation',catalogFilter='all',catalogQuery='',manageTarget;
let wizardProgram=null,wizardStep=0,wizardVisited=0,wizardDirty=false;
function selectEditor(id){selected=id;activeTab='presentation';renderEditor();message('');window.scrollTo({top:0,behavior:'instant'});}
function renderOverview(){
 const editor=$('#editor');editor.replaceChildren();$('#page-title').textContent='Academia';$('#page-description').textContent='Organiza tus programas y prepara la siguiente edición de tu web.';
 const guide=el('div',{class:'cms-guide'},[el('strong',{text:'Tu flujo de trabajo'}),el('span',{text:'1. Edita o crea un programa'}),el('span',{text:'2. Guarda y revisa la vista previa'}),el('span',{text:'3. Publica la edición'})]);editor.append(guide);
 const shortcuts=el('div',{class:'cms-shortcuts'});for(const [id,title,desc] of [['academy','Portada de Academia','Configura el banner y la presentación del catálogo.'],['upcoming','Próximas convocatorias','Prepara las fechas y el contacto de próximas ediciones.']]){const b=el('button',{type:'button',class:'cms-shortcut'},[el('strong',{text:title}),el('span',{text:desc}),el('span',{class:'shortcut-arrow',text:'→','aria-hidden':'true'})]);b.addEventListener('click',()=>selectEditor(id));shortcuts.append(b);}editor.append(shortcuts);
 const head=el('div',{class:'cms-catalog-head'},[el('div',{},[el('h2',{text:'Tus programas'}),el('p',{text:'Busca un programa, edita su contenido o inicia uno nuevo.'})])]);const create=el('button',{type:'button',id:'new-program',class:'button primary',text:'+ Crear programa'});create.addEventListener('click',openCreateDialog);head.append(create);editor.append(head);
 const filters=el('div',{class:'catalog-filters','aria-label':'Filtrar programas'});const cards=el('div',{class:'cms-program-grid'});const count=el('p',{class:'catalog-count',id:'catalog-count'});
 const search=el('input',{type:'search',placeholder:'Buscar por nombre o categoría…','aria-label':'Buscar programas',id:'program-search'});search.value=catalogQuery;search.addEventListener('input',()=>{catalogQuery=search.value;drawCards();});
 function drawCards(){cards.replaceChildren();const list=data.programs.filter(p=>(catalogFilter==='all'?visibility(p)!=='deleted':visibility(p)===catalogFilter)&&(!catalogQuery||[p.title,p.category].join(' ').toLocaleLowerCase('es').includes(catalogQuery.toLocaleLowerCase('es'))));count.textContent=list.length+' '+(list.length===1?'programa':'programas')+' en esta vista';
  for(const p of list){const card=el('article',{class:'cms-program-card'+(visibility(p)==='deleted'?' is-trash':'')});const select=el('button',{type:'button',class:'cms-program-select','aria-label':'Editar '+p.title},[el('img',{src:asset(p.imageSmall),alt:'',loading:'lazy'}),el('span',{class:'cms-program-info'},[el('small',{class:'visibility-badge '+visibility(p),text:visibilityLabels[visibility(p)]}),el('strong',{text:p.title}),el('span',{text:p.hours+' horas · '+p.sessions+' sesiones'}),el('span',{class:'program-state',text:publishedIds.includes(p.id)?statuses[p.status]:'Nuevo · borrador'})])]);select.disabled=visibility(p)==='deleted';select.addEventListener('click',()=>selectEditor(p.id));card.append(select);const actions=el('div',{class:'cms-card-actions'});
   if(visibility(p)==='deleted'){const restore=el('button',{type:'button',text:'Restaurar programa',class:'card-primary'});restore.addEventListener('click',()=>manageProgram(p,'restore'));actions.append(restore);}else{for(const [text,kind] of [['Editar','edit'],[visibility(p)==='public'?'Deshabilitar':'Habilitar','toggle'],['Eliminar','delete']]){const b=el('button',{type:'button',text,class:kind==='edit'?'card-primary':''});b.addEventListener('click',()=>kind==='edit'?selectEditor(p.id):manageProgram(p,kind));actions.append(b);}}card.append(actions);cards.append(card);
  }if(!list.length)cards.append(el('div',{class:'cms-empty'},[el('h3',{text:catalogFilter==='deleted'?'La papelera está vacía':'No encontramos programas'}),el('p',{text:catalogQuery?'Prueba con otro nombre o borra la búsqueda.':'Crea un programa o cambia el filtro para explorar tu catálogo.'})]));
 }
 for(const [key,title] of [['all','Todos'],['public','Visibles'],['hidden','Deshabilitados'],['deleted','Papelera']]){const n=data.programs.filter(p=>key==='all'?visibility(p)!=='deleted':visibility(p)===key).length;const b=el('button',{type:'button',class:catalogFilter===key?'active':'','aria-pressed':String(catalogFilter===key),text:title+' · '+n});b.addEventListener('click',()=>{catalogFilter=key;renderOverview();});filters.append(b);}
 editor.append(el('div',{class:'cms-catalog-toolbar'},[filters,search]),count,cards);drawCards();
}
function manageProgram(p,kind){
 $('#manage-error').textContent='';manageTarget={p,kind,area};const removing=kind==='delete',restoring=kind==='restore',hiding=kind==='toggle'&&visibility(p)==='public';$('#manage-title').textContent=removing?'¿Enviar a la papelera?':restoring?'¿Restaurar este programa?':hiding?'¿Deshabilitar este programa?':'¿Mostrar este programa en la web?';
 $('#manage-description').textContent='“'+p.title+'”. '+(removing?'Se retirará del catálogo y su página dejará de estar disponible. Su contenido quedará en la papelera para recuperarlo.':restoring?'Volverá a tu catálogo como deshabilitado. Puedes editarlo y habilitarlo cuando esté listo.':hiding?'Se ocultará del catálogo y se desactivará su página de inscripción. Conservarás todo el contenido para reactivarlo.':'Aparecerá en el catálogo y en el menú de Academia. Revisa su contenido antes de publicar.');
 if(area==='publications'){$('#manage-title').textContent=removing?'¿Enviar la publicación a la papelera?':restoring?'¿Restaurar la publicación?':hiding?'¿Deshabilitar la publicación?':'¿Mostrar la publicación?';$('#manage-description').textContent='“'+p.title+'”. '+(removing?'Se retirará de la biblioteca. Podrás recuperarla desde la papelera.':restoring?'Volverá a tu biblioteca como deshabilitada.':hiding?'Se ocultará de la biblioteca sin perder sus datos.':'Si ya se publicó, se mostrará esa versión. Publica la edición para aplicar contenido nuevo.');}
 $('#manage-confirm').textContent=removing?'Enviar a la papelera':restoring?'Restaurar':hiding?'Deshabilitar':'Habilitar';$('#manage-notice').textContent=publishedIds.includes(p.id)||area==='publications'?'Si este contenido ya se publicó, la visibilidad de la versión publicada cambiará de inmediato en la web de prueba. Tus otros cambios seguirán como borrador.':'Se guardará en el borrador. Publica la edición para mostrar este contenido nuevo en la web.';$('#manage-dialog').showModal();
}
$('#manage-dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});
$('#manage-cancel').addEventListener('click',()=>$('#manage-dialog').close());
$('#manage-confirm').addEventListener('click',async()=>{if(busy)return;if(pendingUploads){message('Espera a que terminen de subir los archivos.',true);return;}const {p,kind,area:targetArea}=manageTarget;const state=kind==='delete'?'deleted':kind==='restore'?'hidden':visibility(p)==='public'?'hidden':'public';busy=true;const locked=[...document.querySelectorAll('#editor button:not(:disabled),#editor input:not(:disabled),#editor textarea:not(:disabled),#editor select:not(:disabled),#navigation button:not(:disabled),.actions button:not(:disabled)')];locked.forEach(x=>x.disabled=true);$('#manage-confirm').disabled=true;
 try{const next=clone(data),records=targetArea==='academy'?next.programs:next.publications.items;records.find(x=>x.id===p.id).visibility=state;const r=await request('/api/visibility',{data:next,revision,area:targetArea,id:p.id,visibility:state});data=next;revision=r.revision;lastSaved=r.updated;unsaved=false;draftDirty=r.dirty;$('#manage-dialog').close();if(kind==='delete')selected='overview';renderEditor();updateStatus();message(r.applied?'Visibilidad actualizada en la web de prueba. Los demás cambios continúan en el borrador.':'Cambio guardado en el borrador. Publica la edición para mostrar este contenido nuevo.');}catch(e){$('#manage-error').textContent=e.message;}finally{busy=false;locked.forEach(x=>x.disabled=false);$('#manage-confirm').disabled=false;}
});
function asset(value){return value.startsWith('https://')?value:'/'+value;}
function field(obj,key,path){const value=obj[key];const name=labels[key]||(typeof key==='number'?'Texto del elemento':key);
 if(Array.isArray(value))return collection(obj,key,path);
 if(value&&typeof value==='object'){const box=el('div',{class:'nested'},[el('h3',{text:name}),objectFields(value,path)]);if(['certificate','lab'].includes(key)){const remove=el('button',{type:'button',class:'add-item',text:'Desactivar sección'});remove.addEventListener('click',()=>{obj[key]=null;markChanged();renderEditor();});box.append(remove);}return box;}
 const wrapper=el('div',{class:'field'+(typeof value==='string'&&value.length>90?' wide':'')+(imageKeys.has(key)?' image-field':'')});
 const label=el('label',{text:name});const numeric=typeof value==='number'||['regular','launch'].includes(key);let input;
 if(key==='status'||key==='currency'||key==='binding'){input=el('select');const choices=key==='status'?statuses:key==='currency'?{USD:'USD'}:{'':'Valor manual',hours:'Horas del programa',sessions:'Sesiones del programa',start:'Fecha del programa'};for(const [val,text]of Object.entries(choices))input.append(el('option',{value:val,text}));input.value=value||'';}
 else if(typeof value==='boolean'){input=el('input',{type:'checkbox'});input.checked=value;}
 else {const multiline=!imageKeys.has(key)&&!String(key).toLowerCase().endsWith('url')&&(String(value||'').length>90||['description','subtitle','cardDescription','introText','registrationNote','paragraphs','points'].includes(key));input=el(multiline?'textarea':'input',{...(multiline?{rows:3}:{type:key==='startDate'?'date':['accent','accentDark','soft','navy'].includes(key)?'color':numeric?'number':'text'}),...(numeric?{min:0,step:['hours','sessions','pages'].includes(key)?'1':'0.01'}:{})});input.value=value??'';}
 input.dataset.path=path.join('.');input.setAttribute('aria-label',name);
 if(key==='id'||key==='slug'&&publishedIds.includes(obj.id)){input.readOnly=true;}
 const onInput=()=>{if(input.type==='checkbox')obj[key]=input.checked;else if(numeric)obj[key]=input.value===''?null:Number(input.value);else obj[key]=input.value;markChanged();};
 input.addEventListener('input',onInput);label.append(input);wrapper.append(label);
 if(key==='slug')wrapper.append(el('div',{class:'field-hint',text:publishedIds.includes(obj.id)?'URL conservada para mantener los enlaces existentes.':'Ruta pública. Usa letras minúsculas, números y guiones.'}));
 if(key==='launchEndsAt')wrapper.append(el('div',{class:'field-hint',text:'Ejemplo: 2027-03-01T00:00:00-05:00. La promoción se retira al vencer.'}));
 if(value===null&&!numeric&&!['startDate','launchEndsAt'].includes(key)){input.disabled=true;wrapper.append(el('div',{class:'field-hint',text:'Esta sección no está activada en este programa.'}));const template=data.programs.find(p=>p[key]&&typeof p[key]==='object');if(template&&['certificate','lab'].includes(key)){const add=el('button',{type:'button',class:'add-item',text:'Activar sección'});add.addEventListener('click',()=>{obj[key]=clone(template[key]);markChanged();renderEditor();});wrapper.append(add);}}
 if(key==='pdfUrl'){wrapper.append(pdfUploader(obj,input));}
 if(imageKeys.has(key)){const img=el('img',{src:asset(String(value||'')),alt:'Vista previa de '+name});img.addEventListener('error',()=>img.hidden=true);input.addEventListener('input',()=>{img.hidden=false;img.src=asset(input.value);});const upload=el('input',{type:'file',accept:'image/png,image/jpeg,image/webp','aria-label':'Subir '+name});upload.addEventListener('change',async()=>{if(!upload.files[0])return;pendingUploads++;try{const file=upload.files[0];if(file.size>5*1024*1024)throw Error('La imagen debe pesar menos de 5 MB.');upload.disabled=true;const bytes=new Uint8Array(await file.arrayBuffer());let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await request('/api/upload',{content:btoa(str)});obj[key]=r.path;input.value=r.path;img.hidden=false;img.src=asset(r.path);markChanged();message('Imagen subida. Guarda el borrador para conservarla en este campo.');}catch(e){message(e.message,true);}finally{pendingUploads--;upload.disabled=false;upload.value='';}});wrapper.append(img,upload,el('div',{class:'field-hint',text:'PNG, JPG o WebP · máximo 5 MB. Sube una imagen o indica una URL HTTPS.'}));}
 return wrapper;
}
function objectFields(obj,path=[],keys=Object.keys(obj)){const grid=el('div',{class:'fields'});for(const key of keys)grid.append(field(obj,key,[...path,key]));return grid;}
function blank(value){if(Array.isArray(value))return value.map(blank);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,imageKeys.has(k)||k==='binding'?v:blank(v)]));if(typeof value==='number')return value;if(typeof value==='string')return '';return value;}
function outcomeContext(path){
 const root=path[0]==='wizard'?wizardProgram:path[0]==='programs'?data.programs[path[1]]:null;
 return root&&path.slice(-2).join('.')==='outcomes.items'?root.outcomes:null;
}
function collection(obj,key,path){const values=obj[key];const box=el('div',{class:'collection'});box.append(el('h3',{text:labels[key]||key}));let template=values.length?clone(values[values.length-1]):key==='tools'?{title:'',description:''}:'';
 const draw=()=>{box.replaceChildren(el('h3',{text:labels[key]||key}));values.forEach((value,i)=>{const item=el('div',{class:'collection-item'});const tools=el('div',{class:'item-tools'});for(const [text,title,handler]of [['↑','Mover arriba',()=>{if(i){[values[i-1],values[i]]=[values[i],values[i-1]];const outcome=outcomeContext(path);if(outcome)outcome.groups.forEach(g=>g.items=g.items.map(n=>n===i?i-1:n===i-1?i:n));markChanged();draw();}}],['↓','Mover abajo',()=>{if(i<values.length-1){[values[i+1],values[i]]=[values[i],values[i+1]];const outcome=outcomeContext(path);if(outcome)outcome.groups.forEach(g=>g.items=g.items.map(n=>n===i?i+1:n===i+1?i:n));markChanged();draw();}}],['Quitar','Quitar elemento',()=>{const outcome=outcomeContext(path);if(outcome&&values.length===1){message('Conserva al menos una competencia en el programa.',true);return;}values.splice(i,1);if(outcome)outcome.groups.forEach(g=>g.items=g.items.filter(n=>n!==i).map(n=>n>i?n-1:n));markChanged();draw();}]]){const b=el('button',{type:'button',text,'aria-label':title+' '+(i+1)});b.addEventListener('click',handler);tools.append(b);}item.append(el('div',{class:'item-head'},[el('strong',{text:value&&typeof value==='object'?(value.title||value.name||'Elemento '+(i+1)):'Elemento '+(i+1)}),tools]));if(value&&typeof value==='object'&&!Array.isArray(value))item.append(objectFields(value,[...path,i]));else item.append(field(values,i,[...path,i]));box.append(item);});const add=el('button',{type:'button',class:'add-item',text:'＋ Añadir elemento'});add.addEventListener('click',()=>{values.push(blank(template));const outcome=outcomeContext(path);if(outcome){if(!outcome.groups.length)outcome.groups.push({title:'Competencias',items:[]});outcome.groups[0].items.push(values.length-1);}markChanged();draw();});box.append(add);};draw();return box;}
function panel(title,obj,path,keys,open=false){const d=el('details',{class:'panel'},[el('summary',{text:title}),el('div',{class:'panel-body'},[objectFields(obj,path,keys)])]);d.open=open;return d;}
function renderEditor(){
 if(area==='publications'){renderPublicationEditor();return;}
 if(selected==='overview'){renderOverview();return;}const editor=$('#editor');editor.replaceChildren();const back=el('button',{type:'button',class:'cms-back',text:'← Academia / '+(selected==='academy'?'Portada':selected==='upcoming'?'Convocatorias':'Programas')});back.addEventListener('click',()=>selectEditor('overview'));editor.append(back);
 const p=data.programs.find(x=>x.id===selected);$('#page-title').textContent=p?p.title:selected==='academy'?'Portada de Academia':'Próximas convocatorias';$('#page-description').textContent=p?'Edita una sección a la vez. Tus cambios se conservan al cambiar de pestaña.':'Edita el contenido y revisa la vista previa antes de publicar.';
 if(!p){const section=data[selected];if(selected==='academy')editor.append(panel('Banner de Academia',section,[selected],['title','subtitle','image','imageSmall','imageAlt'],true),panel('Presentación del catálogo',section,[selected],['programsTitle','programsText']),panel('Beneficios del banner',section,[selected],['features']));else editor.append(panel('Presentación y contacto',section,[selected],Object.keys(section),true));return;}
 const summary=el('div',{class:'editor-program-summary'},[el('img',{src:asset(p.imageSmall),alt:''}),el('div',{},[el('span',{class:'visibility-badge '+visibility(p),text:visibilityLabels[visibility(p)]}),el('p',{text:p.category+' · '+p.hours+' horas · '+p.sessions+' sesiones'})])]);const tools=el('div',{class:'editor-program-tools'});for(const [title,kind] of [[visibility(p)==='public'?'Deshabilitar':'Habilitar','toggle'],['Eliminar','delete']]){const button=el('button',{type:'button',class:'button secondary',text:title});button.addEventListener('click',()=>manageProgram(p,kind));tools.append(button);}summary.append(tools);editor.append(summary);
 const tabs=el('div',{class:'editor-tabs',role:'tablist','aria-label':'Secciones del programa'});const pane=el('div',{id:'program-pane',role:'tabpanel','aria-labelledby':'editor-tab-'+activeTab,class:'editor-pane'});
 for(const [key,title] of editorTabs){const b=el('button',{type:'button',id:'editor-tab-'+key,role:'tab','aria-selected':String(activeTab===key),'aria-controls':'program-pane',tabindex:activeTab===key?'0':'-1',text:title});const change=()=>{activeTab=key;renderEditor();$('#editor-tab-'+key).focus();};b.addEventListener('click',change);b.addEventListener('keydown',e=>{if(!['ArrowRight','ArrowLeft','Home','End'].includes(e.key))return;e.preventDefault();let i=editorTabs.findIndex(x=>x[0]===key);i=e.key==='Home'?0:e.key==='End'?editorTabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+editorTabs.length)%editorTabs.length;activeTab=editorTabs[i][0];renderEditor();$('#editor-tab-'+activeTab).focus();});tabs.append(b);}editor.append(tabs,pane);
 const path=['programs',data.programs.indexOf(p)];const descriptions={presentation:'Nombre, presentación y dirección de la página.',media:'Portadas, fondos y colores que identifican al programa.',enrollment:'Fechas, duración, precios y enlaces de inscripción.',content:'Revisa los aprendizajes, el temario y las competencias.',teaching:'Docentes, metodología y herramientas de aprendizaje.',closing:'Certificación, respaldo de MALBA y llamado final.'};pane.append(el('p',{class:'editor-context',text:descriptions[activeTab]}));
 if(activeTab==='presentation'){pane.append(panel('Presentación',p,path,['title','category','description','cardDescription','edition'],true),panel('Dirección de la página',p,path,['slug']));const order=el('div',{class:'program-order'});const list=data.programs.filter(x=>visibility(x)!=='deleted'),index=list.indexOf(p);order.append(el('span',{text:'Posición '+(index+1)+' de '+list.length}));for(const [text,delta] of [['← Mover antes',-1],['Mover después →',1]]){const b=el('button',{type:'button',text});b.disabled=index+delta<0||index+delta>=list.length;b.addEventListener('click',()=>{const i=data.programs.indexOf(p),j=data.programs.indexOf(list[index+delta]);[data.programs[i],data.programs[j]]=[data.programs[j],data.programs[i]];markChanged();renderEditor();});order.append(b);}pane.append(order);}
 if(activeTab==='media')pane.append(panel('Portadas del programa',p,path,['image','imageSmall','imageAlt'],true),panel('Fondos y colores',p,path,['imageWide','sectionImage','theme']));
 if(activeTab==='enrollment'){pane.append(panel('Fechas y modalidad',p,path,['status','startDate','startLabel','hours','sessions','modality','schedule','registrationNote'],true));const prices=panel('Precios y enlaces',p,path,['pricing','brochureUrl','checkoutUrl','whatsappUrl']);prices.querySelector('.panel-body').prepend(el('p',{class:'notice',text:'Los precios de la web deben coincidir con los cobros de WooCommerce.'}));pane.append(prices);}
 const groups={content:['learning','curriculum','specialization','outcomes'],teaching:['instructors','methodology','applied','lab'],closing:['certificate','proof','final']};if(groups[activeTab])groups[activeTab].forEach((key,i)=>pane.append(panel(labels[key],p,path,[key],i===0)));
 const footer=el('div',{class:'editor-footer'},[el('span',{text:'Guarda antes de cerrar. Publicar es un paso independiente.'})]);const save=el('button',{type:'button',class:'button primary',text:'Guardar borrador'});save.addEventListener('click',()=>action('save'));footer.append(save);editor.append(footer);
}
async function action(kind){if(busy)return;busy=true;document.querySelectorAll('.actions button').forEach(b=>b.disabled=true);message(kind==='preview'?'Preparando vista previa…':kind==='publish'?'Publicando los cambios…':'Guardando borrador…');let previewWindow;if(kind==='preview')previewWindow=window.open('about:blank','_blank');try{const snapshot=clone(data),started=changeCounter;const r=await request('/api/'+(kind==='save'?'draft':kind),{data:snapshot,revision});if(kind==='preview'){if(previewWindow){previewWindow.opener=null;const program=data.programs.find(p=>p.id===selected);previewWindow.location.href=area==='publications'?r.url.replace(/academia\/$/,'publicaciones/'):program?r.url.replace(/academia\/$/,program.slug+'/'):r.url;}else message('Vista previa lista. Permite ventanas emergentes para abrirla.');}else{revision=r.revision;lastSaved=r.updated;unsaved=changeCounter!==started;draftDirty=kind!=='publish'||unsaved;if(kind==='publish')publishedIds=snapshot.programs.map(p=>p.id);updateStatus();message(kind==='publish'?'Cambios publicados. Ya puedes verlos en la web de prueba.':'Borrador guardado. La web pública todavía conserva la edición anterior.');renderNavigation();if(selected==='overview')renderEditor();}}catch(e){previewWindow?.close();message(e.message,true);}finally{busy=false;document.querySelectorAll('.actions button').forEach(b=>b.disabled=false);}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('#login-error').textContent='';try{const form=new FormData(e.target);const r=await request('/api/login',Object.fromEntries(form));csrf=r.csrf;$('#user-label').textContent='Sesión de '+r.username;await loadContent();e.target.reset();$('#login').hidden=true;$('#app').hidden=false;}catch(err){$('#login-error').textContent=err.message;}finally{b.disabled=false;}});
$('#save').addEventListener('click',()=>action('save'));$('#preview').addEventListener('click',()=>action('preview'));
$('#publish').addEventListener('click',()=>{$('#publish-dialog').returnValue='';$('#publish-dialog').showModal();});$('#publish-dialog').addEventListener('close',()=>{if($('#publish-dialog').returnValue==='publish')action('publish');});
$('#logout').addEventListener('click',async()=>{if(unsaved&&!confirm('Tienes cambios sin guardar. ¿Cerrar sesión?'))return;try{await request('/api/logout',{});unsaved=false;data=null;showLogin();}catch(e){message(e.message,true);}});
$('#history').addEventListener('click',async()=>{try{const history=await request('/api/history');const list=$('#history-list');list.replaceChildren();history.forEach((h,i)=>{const text=el('div',{text:date(h.created)},[el('small',{text:h.username+(i===0?' · Publicación actual':'')})]);const b=el('button',{type:'button',class:'button secondary',text:'Recuperar'});b.addEventListener('click',async()=>{if(!confirm('¿Cargar esta publicación como borrador? Reemplazará las ediciones sin publicar.'))return;try{const r=await request('/api/restore',{id:h.id,revision});data=r.data;revision=r.revision;lastSaved=r.updated;unsaved=false;draftDirty=true;selected='overview';renderNavigation();renderEditor();updateStatus();$('#history-dialog').close();message('Versión recuperada como borrador. Revísala antes de publicar.');}catch(e){message(e.message,true);$('#history-dialog').close();}});list.append(el('div',{class:'history-item'},[text,b]));});$('#history-dialog').showModal();}catch(e){message(e.message,true);}});
const wizardSteps=['Datos','Imágenes','Inscripciones','Contenido','Revisión'];let wizardTemplateId;
function slugify(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,150).replace(/-$/,'');}
function makeWizardProgram(template){const p=clone(template);Object.assign(p,{id:'programa-'+crypto.randomUUID().slice(0,8),slug:'',title:'',description:'',cardDescription:'',visibility:'hidden',status:'proximamente',startDate:null,startLabel:'Fecha por confirmar',schedule:'',checkoutUrl:'',brochureUrl:'',whatsappUrl:template.whatsappUrl.split('?')[0],edition:'Primera edición',registrationNote:'Consulta las próximas fechas de este programa.'});Object.assign(p.pricing,{regular:null,launch:null,launchEndsAt:null,note:''});return p;}
function openCreateDialog(){if(busy)return;wizardTemplateId=(data.programs.find(p=>visibility(p)!=='deleted')||data.programs[0]).id;wizardProgram=makeWizardProgram(data.programs.find(p=>p.id===wizardTemplateId));wizardStep=0;wizardVisited=0;wizardDirty=false;renderWizard();$('#create-dialog').showModal();$('#wizard-body input[data-path="wizard.title"]').focus();}
function wizardError(text){const error=$('#wizard-error');error.textContent=text;error.hidden=!text;if(text)error.scrollIntoView({block:'nearest'});}
function renderWizard(){
 wizardError('');const progress=$('#wizard-progress');progress.replaceChildren();wizardSteps.forEach((title,i)=>{const b=el('button',{type:'button',class:i===wizardStep?'active':i<wizardStep?'complete':'',text:(i+1)+'. '+title,'aria-current':i===wizardStep?'step':'false'});b.disabled=i>wizardVisited;b.addEventListener('click',()=>{if(busy)return;if(i<=wizardStep||validateWizardStep()){wizardStep=i;renderWizard();}});progress.append(b);});const body=$('#wizard-body');body.replaceChildren();const titles=['Define tu programa','Dale una identidad visual','Configura la próxima edición','Revisa el contenido de aprendizaje','Tu programa está listo para guardarse'];body.append(el('h3',{text:titles[wizardStep]}));const p=wizardProgram,path=['wizard'];
 if(wizardStep===0){const label=el('label',{text:'Usar diseño y estructura de'});const select=el('select',{'aria-label':'Programa de referencia'});for(const source of data.programs.filter(x=>visibility(x)!=='deleted'||x.id===wizardTemplateId))select.append(el('option',{value:source.id,text:source.title}));select.value=wizardTemplateId;select.addEventListener('change',()=>{const previous=wizardProgram;wizardTemplateId=select.value;wizardProgram=makeWizardProgram(data.programs.find(x=>x.id===select.value));for(const k of ['title','slug','description','cardDescription'])wizardProgram[k]=previous[k];wizardDirty=true;renderWizard();});label.append(select);body.append(el('div',{class:'wizard-template'},[label,el('p',{text:'La plantilla aporta el diseño, los colores y una estructura de contenidos que podrás adaptar.'})]),objectFields(p,path,['title','category','description','slug']));for(const key of ['title','category','description','slug'])body.querySelector('[data-path="wizard.'+key+'"]').required=true;
  const title=body.querySelector('[data-path="wizard.title"]'),slug=body.querySelector('[data-path="wizard.slug"]');let manualSlug=p.slug&&p.slug!==slugify(p.title);title.addEventListener('input',()=>{if(!manualSlug){p.slug=slugify(title.value);slug.value=p.slug;}});slug.addEventListener('input',()=>manualSlug=true);slug.pattern='[a-z0-9-]+';slug.maxLength=150;title.maxLength=150;
 }
 if(wizardStep===1){body.append(el('p',{class:'editor-context',text:'Prepara una portada para escritorio y otra para celular. También puedes ajustar las imágenes después de crear el borrador.'}),objectFields(p,path,['image','imageSmall','imageAlt']),panel('Fondos y colores (opcional)',p,path,['imageWide','sectionImage','theme']));}
 if(wizardStep===2){body.append(el('p',{class:'editor-context',text:'Próximamente mantiene el programa visible sin habilitar la compra. El nuevo borrador se crea deshabilitado, independientemente de sus inscripciones.'}),panel('Fechas y modalidad',p,path,['status','startDate','startLabel','hours','sessions','modality','schedule'],true),panel('Precios y enlaces',p,path,['pricing','checkoutUrl','brochureUrl','whatsappUrl']));for(const key of ['hours','sessions']){const input=body.querySelector('[data-path="wizard.'+key+'"]').required=true;body.querySelector('[data-path="wizard.'+key+'"]').min='1';}}
 if(wizardStep===3){body.append(el('p',{class:'notice',text:'Estos contenidos provienen de “'+data.programs.find(x=>x.id===wizardTemplateId).title+'”. Adáptalos al nuevo programa. Podrás continuar editándolos mientras permanezca deshabilitado.'}));for(const [i,key]of ['learning','curriculum','instructors','outcomes'].entries())body.append(panel(labels[key],p,path,[key],i===0));}
 if(wizardStep===4){body.append(el('div',{class:'wizard-review'},[el('img',{src:asset(p.imageSmall),alt:''}),el('div',{},[el('span',{class:'visibility-badge hidden',text:'Se creará deshabilitado'}),el('h3',{text:p.title}),el('p',{text:p.category+' · '+p.hours+' horas · '+p.sessions+' sesiones'}),el('p',{text:'Página: /'+p.slug+'/'}),el('p',{text:statuses[p.status]+' · '+(p.startDate||p.startLabel)})])]),el('p',{class:'notice',text:'Crear y guardar conserva un borrador privado. Luego puedes revisar la página, habilitar el programa y publicar la edición.'}));const label=el('label',{class:'wizard-review-check'});const check=el('input',{type:'checkbox',name:'reviewed','aria-label':'He revisado los datos y sé que el contenido proviene de una plantilla'});label.append(check,el('span',{text:'He revisado los datos y sé que el contenido proviene de una plantilla.'}));body.append(label);}
 $('#wizard-back').hidden=wizardStep===0;$('#wizard-next').textContent=wizardStep===4?'Crear y guardar borrador':'Continuar →';$('#wizard-position').textContent='Paso '+(wizardStep+1)+' de 5';$('#create-dialog').scrollTop=0;
}
function validateWizardStep(){
 wizardError('');if(pendingUploads){wizardError('Espera a que termine la carga de la imagen.');return false;}for(const input of $('#wizard-body').querySelectorAll('input:not([type=file]),textarea,select')){if(!input.reportValidity())return false;}
 const p=wizardProgram;if(wizardStep===0){if(!p.title.trim()||!p.category.trim()||!p.description.trim()){wizardError('Completa el nombre, la categoría y la descripción.');return false;}if(!/^[a-z0-9-]+$/.test(p.slug)||data.programs.some(x=>x.slug===p.slug)||['academia','publicaciones','dashboard','soluciones-digitales','assets','content','api','scripts','tests','docs','cms-preview'].includes(p.slug)){wizardError('Elige una URL distinta, con letras minúsculas, números y guiones. Las URLs de la papelera también se conservan.');return false;}}
 if(wizardStep===2&&(!(p.hours>0&&p.hours<=2000)||!(p.sessions>0&&p.sessions<=500))){wizardError('Indica una duración entre 1 y 2000 horas y entre 1 y 500 sesiones.');return false;}
 if(wizardStep===4&&!$('#create-form [name=reviewed]').checked){wizardError('Confirma que revisaste los datos antes de guardar el programa.');$('#create-form [name=reviewed]').focus();return false;}return true;
}
$('#wizard-back').addEventListener('click',()=>{if(busy)return;wizardStep--;renderWizard();});
$('#create-form').addEventListener('submit',async e=>{e.preventDefault();if(busy||!validateWizardStep())return;if(wizardStep<4){wizardStep++;wizardVisited=Math.max(wizardVisited,wizardStep);renderWizard();return;}
 busy=true;$('#create-form').querySelectorAll('button,input').forEach(e=>e.disabled=true);$('#wizard-next').disabled=true;$('#wizard-next').textContent='Guardando…';const next=clone(data);const p=clone(wizardProgram);if(!p.cardDescription)p.cardDescription=p.description;next.programs.push(p);
 try{const r=await request('/api/draft',{data:next,revision});data=next;revision=r.revision;lastSaved=r.updated;unsaved=false;draftDirty=true;selected=p.id;activeTab='presentation';wizardDirty=false;$('#create-dialog').close();wizardProgram=null;renderEditor();updateStatus();message('Programa creado y guardado. Revisa sus contenidos y la vista previa; habilítalo y publica cuando esté listo.');window.scrollTo({top:0,behavior:'instant'});}catch(err){wizardError(err.message);}finally{busy=false;$('#create-form').querySelectorAll('button,input').forEach(e=>e.disabled=false);$('#wizard-next').disabled=false;$('#wizard-next').textContent='Crear y guardar borrador';}
});
function cancelWizard(e){if(busy){e?.preventDefault();return;}if(wizardDirty&&!confirm('¿Descartar la creación de este programa? Los programas existentes se conservan.')){e?.preventDefault();return;}$('#create-dialog').close();wizardProgram=null;wizardDirty=false;}
$('#create-dialog').addEventListener('cancel',e=>{e.preventDefault();cancelWizard(e);});$('#create-dialog .dialog-close').addEventListener('click',cancelWizard);
function pdfUploader(obj,input){const box=el('div',{class:'pdf-upload'}),link=el('a',{href:obj.pdfUrl?asset(obj.pdfUrl):'#',target:'_blank',rel:'noopener',text:'Abrir PDF actual ↗'});link.hidden=!obj.pdfUrl;input.addEventListener('input',()=>{link.hidden=!input.value;link.href=input.value?asset(input.value):'#';});const file=el('input',{type:'file',accept:'application/pdf,.pdf','aria-label':'Subir archivo PDF'});file.addEventListener('change',async()=>{if(!file.files[0])return;pendingUploads++;file.disabled=true;try{const f=file.files[0];if(f.size>20*1024*1024)throw Error('Usa un PDF de hasta 20 MB.');const bytes=new Uint8Array(await f.arrayBuffer());let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));const r=await request('/api/upload-pdf',{content:btoa(str)});obj.pdfUrl=r.path;input.value=r.path;link.href=asset(r.path);link.hidden=false;markChanged();$('#publication-error').textContent='PDF subido. Guarda para conservar el archivo.';message('PDF subido. Guarda el borrador para conservarlo.');}catch(e){$('#publication-error').textContent=e.message;message(e.message,true);}finally{pendingUploads--;file.disabled=false;file.value='';}});box.append(file,link,el('p',{class:'field-hint',text:'PDF · hasta 20 MB. También puedes indicar una URL HTTPS.'}));return box;}
function renderPublicationsOverview(){const editor=$('#editor');editor.replaceChildren();$('#page-title').textContent='Publicaciones';$('#page-description').textContent='Comparte las revistas de MALBA y mantén tu biblioteca al día.';
 const banner=el('button',{type:'button',class:'cms-shortcut'},[el('strong',{text:'Banner y catálogo'}),el('span',{text:'Edita los textos y las imágenes de la página de Publicaciones.'}),el('span',{class:'shortcut-arrow',text:'→'})]);banner.addEventListener('click',()=>selectEditor('publication-banner'));editor.append(el('div',{class:'cms-shortcuts'},[banner]));
 const add=el('button',{type:'button',class:'button primary',id:'new-publication',text:'+ Añadir publicación'});add.addEventListener('click',openPublicationDialog);editor.append(el('div',{class:'cms-catalog-head'},[el('div',{},[el('h2',{text:'Tu biblioteca'}),el('p',{text:'Edita, ordena o añade una revista. Deshabilitar y eliminar actualizan su visibilidad de inmediato.'})]),add]));
 const filters=el('div',{class:'catalog-filters'});for(const [key,label] of [['all','Todas'],['public','Visibles'],['hidden','Deshabilitadas'],['deleted','Papelera']]){const count=data.publications.items.filter(p=>key==='all'?visibility(p)!=='deleted':visibility(p)===key).length;const b=el('button',{type:'button',text:label+' · '+count,class:key===publicationFilter?'active':'','aria-pressed':String(key===publicationFilter)});b.addEventListener('click',()=>{publicationFilter=key;renderPublicationsOverview();});filters.append(b);}
 const search=el('input',{type:'search',placeholder:'Buscar publicación…','aria-label':'Buscar publicaciones'});search.value=publicationQuery;const grid=el('div',{class:'cms-program-grid cms-publication-grid'});
 const draw=()=>{grid.replaceChildren();const records=data.publications.items.filter(p=>(publicationFilter==='all'?visibility(p)!=='deleted':visibility(p)===publicationFilter)&&[p.title,p.edition,p.description].join(' ').toLocaleLowerCase('es').includes(publicationQuery.toLocaleLowerCase('es')));for(const p of records){const select=el('button',{type:'button',class:'cms-program-select','aria-label':'Editar '+p.title},[el('img',{src:asset(p.imageSmall),alt:'',loading:'lazy'}),el('span',{class:'cms-program-info'},[el('small',{class:'visibility-badge '+visibility(p),text:visibilityLabels[visibility(p)]}),el('strong',{text:p.title}),el('span',{text:p.edition+' · '+p.pages+' páginas'})])]);select.disabled=visibility(p)==='deleted';select.addEventListener('click',()=>selectEditor('publication:'+p.id));const actions=el('div',{class:'cms-card-actions'});for(const [title,kind] of visibility(p)==='deleted'?[['Restaurar','restore']]:[['Editar','edit'],[visibility(p)==='public'?'Deshabilitar':'Habilitar','toggle'],['Eliminar','delete']]){const b=el('button',{type:'button',text:title,class:kind==='edit'?'card-primary':''});b.addEventListener('click',()=>kind==='edit'?selectEditor('publication:'+p.id):manageProgram(p,kind));actions.append(b);}grid.append(el('article',{class:'cms-program-card'},[select,actions]));}if(!records.length)grid.append(el('div',{class:'cms-empty'},[el('h3',{text:'No hay publicaciones en esta vista'}),el('p',{text:'Cambia el filtro o añade una publicación.'})]));};search.addEventListener('input',()=>{publicationQuery=search.value;draw();});editor.append(el('div',{class:'cms-catalog-toolbar'},[filters,search]),grid);draw();
}
function renderPublicationEditor(){if(selected==='overview'){renderPublicationsOverview();return;}const editor=$('#editor');editor.replaceChildren();const back=el('button',{type:'button',class:'cms-back',text:'← Publicaciones / Biblioteca'});back.addEventListener('click',()=>selectEditor('overview'));editor.append(back);$('#page-description').textContent='Guarda, revisa la vista previa y publica los cambios de contenido.';
 if(selected==='publication-banner'){$('#page-title').textContent='Banner de Publicaciones';editor.append(panel('Banner',data.publications,['publications'],['title','subtitle','image','imageSmall','imageAlt'],true),panel('Catálogo',data.publications,['publications'],['catalogTitle','catalogText'],true));return;}
 const index=data.publications.items.findIndex(p=>'publication:'+p.id===selected),p=data.publications.items[index];if(!p){selected='overview';renderPublicationsOverview();return;}$('#page-title').textContent=p.title;editor.append(el('div',{class:'editor-program-summary'},[el('img',{src:asset(p.imageSmall),alt:''}),el('span',{class:'visibility-badge '+visibility(p),text:visibilityLabels[visibility(p)]}),el('a',{href:asset(p.pdfUrl),target:'_blank',rel:'noopener',text:'Abrir PDF ↗'})]));editor.append(panel('Información de la revista',p,['publications','items',index],['title','edition','description','pages'],true),panel('Portada',p,['publications','items',index],['image','imageSmall','imageAlt'],true),panel('Archivo PDF',p,['publications','items',index],['pdfUrl'],true));
 const tools=el('div',{class:'program-order'});for(const [title,delta] of [['← Mover antes',-1],['Mover después →',1]]){const b=el('button',{type:'button',text:title});b.disabled=index+delta<0||index+delta>=data.publications.items.length;b.addEventListener('click',()=>{const items=data.publications.items;[items[index],items[index+delta]]=[items[index+delta],items[index]];markChanged();renderPublicationEditor();});tools.append(b);}for(const [title,kind] of [[visibility(p)==='public'?'Deshabilitar':'Habilitar','toggle'],['Eliminar','delete']]){const b=el('button',{type:'button',text:title});b.addEventListener('click',()=>manageProgram(p,kind));tools.append(b);}editor.append(tools);
}
function openPublicationDialog(){if(busy)return;publicationDraft={id:'revista-'+crypto.randomUUID().slice(0,8),title:'',edition:'',description:'',image:'',imageSmall:'',imageAlt:'',pdfUrl:'',pages:1,visibility:'hidden'};$('#publication-error').textContent='';$('#publication-body').replaceChildren(objectFields(publicationDraft,['newPublication'],['title','edition','description','pages','image','imageAlt','pdfUrl']));$('#publication-dialog').showModal();$('#publication-body input').focus();}
$('#publication-form').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;if(pendingUploads){$('#publication-error').textContent='Espera a que terminen de subir los archivos.';return;}const p=publicationDraft;for(const key of ['title','edition','description','image','imageAlt','pdfUrl'])if(!p[key].trim()){$('#publication-error').textContent='Completa '+labels[key]+'.';return;}p.imageSmall=p.image;const next=clone(data);next.publications.items.unshift(clone(p));busy=true;$('#publication-submit').disabled=true;try{const r=await request('/api/draft',{data:next,revision});data=next;revision=r.revision;lastSaved=r.updated;unsaved=false;draftDirty=true;$('#publication-dialog').close();publicationDraft=null;selectEditor('publication:'+p.id);updateStatus();message('Publicación guardada como deshabilitada. Revisa su PDF, habilítala y publica cuando esté lista.');}catch(e){$('#publication-error').textContent=e.message;}finally{busy=false;$('#publication-submit').disabled=false;}});
function cancelPublication(e){if(busy){e.preventDefault();return;}if(publicationDraft&&Object.values(publicationDraft).some(v=>typeof v==='string'&&v&&!['hidden',publicationDraft.id].includes(v))&&!confirm('¿Descartar la publicación nueva?')){e.preventDefault();return;}$('#publication-dialog').close();publicationDraft=null;}
$('#publication-dialog').addEventListener('cancel',e=>{e.preventDefault();cancelPublication(e);});$('#publication-dialog .dialog-close').addEventListener('click',cancelPublication);
for(const dialog of document.querySelectorAll('dialog:not(#create-dialog):not(#publication-dialog)')){const close=dialog.querySelector('.dialog-close[type="button"]');close?.addEventListener('click',()=>dialog.close());}
window.addEventListener('beforeunload',e=>{if(unsaved){e.preventDefault();e.returnValue='';}});
(async()=>{try{const session=await request('/api/session');if(!session.authenticated){showLogin();return;}csrf=session.csrf;$('#user-label').textContent='Sesión de '+session.username;await loadContent();$('#app').hidden=false;$('#loading').hidden=true;}catch(e){showLogin();$('#login-error').textContent=e.message;}})();
